# Generated by Django 4.2.16 on 2024-11-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0007_remove_busstop_bus_shifts'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busshift',
            name='bus_stops',
            field=models.ManyToManyField(to='geography.busstop'),
        ),
    ]
