# Generated by Django 4.2.16 on 2024-11-25 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0007_remove_busstop_bus_shifts'),
        ('planning', '0002_busshift_bus_stops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busshift',
            name='bus_stops',
        ),
        migrations.CreateModel(
            name='BusStopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('bus_stop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='geography.busstop')),
            ],
        ),
        migrations.AddField(
            model_name='busshift',
            name='bus_stops_times',
            field=models.ManyToManyField(to='planning.busstoptime'),
        ),
    ]
