# Generated by Django 4.2.16 on 2024-11-25 12:42

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_remove_busshift_bus_stops_busstoptime_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='busshift',
            managers=[
                ('bus_shift', django.db.models.manager.Manager()),
            ],
        ),
    ]
