# Generated by Django 4.2.16 on 2024-11-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_alter_busshift_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='busshift',
            managers=[
            ],
        ),
    ]
