# Generated by Django 4.2.16 on 2024-11-25 13:20

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_alter_busshift_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='busshift',
            managers=[
                ('bus_shift', django.db.models.manager.Manager()),
            ],
        ),
    ]
