# Generated by Django 4.2.16 on 2024-11-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_busstop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busstop',
            old_name='place',
            new_name='bus_stop',
        ),
    ]
