# Generated by Django 4.2.16 on 2024-11-25 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0003_rename_place_busstop_bus_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='bus_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_stop', to='geography.place'),
        ),
    ]
