# Generated by Django 4.2.16 on 2024-11-25 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
        ('geography', '0004_alter_busstop_bus_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstop',
            name='bus_shifts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_shift', to='planning.busshift'),
        ),
    ]
