# Generated by Django 4.2.16 on 2024-11-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
        ('geography', '0005_busstop_bus_shifts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busstop',
            name='bus_shifts',
        ),
        migrations.AddField(
            model_name='busstop',
            name='bus_shifts',
            field=models.ManyToManyField(null=True, related_name='bus_shift', to='planning.busshift'),
        ),
    ]
