# Generated by Django 4.2.16 on 2024-11-25 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0006_remove_busstop_bus_shifts_busstop_bus_shifts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busstop',
            name='bus_shifts',
        ),
    ]
